f=open('./gaussian_test.inp','w')
f.write('%chk=monomer.chk\n')
f.write('%nprocshared=4\n')
f.write('%mem=8000mb\n')
f.write('#T wB97XD/def2svpp opt=tight freq int(grid=ultrafine) scf=(verytight,qc) Volume=tight\n')
f.write('\n')
f.write('Monomer\n')
f.write('\n')
xyz = open('./crest_best.xyz')
coord = xyz.readlines()
f.write("0 1\n")
for j in range(int(coord[0].split()[0])):
    f.write(coord[j+2])
f.write('\n')
f.close()
